#!/usr/bin/env python3
"""
OctoPy Onboarding Experience 🐙
Location: scripts/Getting_Started/welcome.py
"""

import os
import io
import sys
import platform
from pathlib import Path
from datetime import datetime

import io

# Force UTF-8 for standard streams to bypass Windows legacy encoding
if sys.platform == "win32":
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')
    sys.stderr = io.TextIOWrapper(sys.stderr.buffer, encoding='utf-8')

# NOTE: rich is required for the styled output
try:
    from rich.console import Console
    from rich.panel import Panel
    from rich.table import Table
    from rich.text import Text
    from rich.status import Status
except ImportError:
    print("Error: 'rich' library not found. Please run 'pip install rich'")
    sys.exit(1)

console = Console(force_terminal=True, color_system="auto")


def intro():
    console.print(
        Panel(
            Text(
                "Welcome to OctoPy 🐙🐍\n\n"
                "This quick walkthrough will show you how OctoPy works, "
                "using real scripts, real output, and a bit of magic 🚀",
                justify="center",
            ),
            border_style="cyan",
            title="OctoPy Onboarding",
            subtitle="First-Run Experience",
        )
    )


def explain_core_concepts():
    console.print("\n[bold cyan]Core Concepts[/bold cyan]\n")

    concepts = [
        ("📁 Folders = Categories",
         "Every subfolder inside [bold]/scripts[/bold] becomes a section in the OctoPy dashboard."),
        ("📡 Live Streaming", "Anything your script prints appears here in real time—even interactive prompts!"),
        ("🛑 The Kill Switch",
         "Press [bold yellow]Ctrl+C[/bold yellow] at any time to terminate a running process.")
    ]

    for title, desc in concepts:
        console.print(f"[bold]{title}[/bold]")
        console.print(f"   {desc}\n")

    input("Press Enter to continue...")


def system_check():
    console.print("\n[bold cyan]System Check[/bold cyan]\n")

    # Information gathering
    python_version = sys.version.split()[0]
    os_info = f"{platform.system()} {platform.release()}"
    cwd = Path.cwd()
    # Your main.py defaults to './scripts'
    scripts_dir = cwd / "scripts"

    table = Table(show_header=True, header_style="bold magenta", expand=True)
    table.add_column("Environment Component")
    table.add_column("Status/Value")

    table.add_row("Python Version", python_version)
    table.add_row("Operating System", os_info)
    table.add_row("OctoPy Root", str(cwd))
    table.add_row("Scripts Folder",
                  "✅ Found" if scripts_dir.exists() else "❌ Missing")

    console.print(table)


def create_hello_world():
    console.print("\n[bold cyan]One Last Trick ✨[/bold cyan]\n")
    console.print(
        "Let's create a new script live. Look at the file tree on the left after this!")

    # This interacts with OctoPy's input bar
    name = input("What is your name? ")
    if not name:
        name = "Explorer"

    scripts_dir = Path.cwd() / "scripts"
    hello_path = scripts_dir / "hello_world.py"

    content = f'''#!/usr/bin/env python3
    
import io
import sys

# Force UTF-8 for standard streams to bypass Windows legacy encoding
if sys.platform == "win32":
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')
    sys.stderr = io.TextIOWrapper(sys.stderr.buffer, encoding='utf-8')

print(f"stdout encoding: {sys.stdout.encoding}")

"""
Hello World – Generated by OctoPy Onboarding
Created: 2026-02-07 11:24
"""
print("Hello, {name}! 👋")
print("You just witnessed OctoPy's dynamic tree updates.")
'''

    try:
        # Create scripts dir if it doesn't exist to avoid OctoPy errors
        scripts_dir.mkdir(exist_ok=True)

        with open(hello_path, "w", encoding="utf-8") as f:
            f.write(content)

        # Ensure executable on Linux/Mac
        if platform.system() != "Windows":
            os.chmod(hello_path, 0o755)

        console.print(
            f"\n[bold green]Success![/bold green] Created: [white]{hello_path.name}[/white]")
    except Exception as e:
        console.print(f"[bold red]Error creating file:[/bold red] {e}")


def main():
    try:
        intro()
        explain_core_concepts()
        system_check()
        create_hello_world()
        console.print(
            "\n[bold cyan]Onboarding Complete![/bold cyan] Happy hacking! 🐙🚀\n")
    except KeyboardInterrupt:
        # Graceful exit for your Ctrl+C binding
        console.print("\n[bold red]Onboarding cancelled by user.[/bold red]")


if __name__ == "__main__":
    main()
