#!/usr/bin/env python3
    
import io
import sys

# Force UTF-8 for standard streams to bypass Windows legacy encoding
if sys.platform == "win32":
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')
    sys.stderr = io.TextIOWrapper(sys.stderr.buffer, encoding='utf-8')

print(f"stdout encoding: utf-8")

"""
Hello World – Generated by OctoPy Onboarding
Created: 2026-02-07 11:24
"""
print("Hello, Sebastian! 👋")
print("You just witnessed OctoPy's dynamic tree updates.")
